{
    "file-format": {
        "meta-header": {
            "xfer": "1.2.840.10008.1.2.1",
            "name": "Little Endian Explicit",
            "element": [{
                "_": "200",
                "tag": "0002,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "FileMetaInformationGroupLength"
            }, {
                "tag": "0002,0001",
                "vr": "OB",
                "vm": "1",
                "len": "2",
                "name": "FileMetaInformationVersion",
                "binary": "hidden"
            }, {
                "_": "1.2.840.10008.5.1.4.1.1.1.2",
                "tag": "0002,0002",
                "vr": "UI",
                "vm": "1",
                "len": "28",
                "name": "MediaStorageSOPClassUID"
            }, {
                "_": "1.2.840.113619.2.227.27331683280.2217131219174320.119",
                "tag": "0002,0003",
                "vr": "UI",
                "vm": "1",
                "len": "54",
                "name": "MediaStorageSOPInstanceUID"
            }, {
                "_": "1.2.840.10008.1.2",
                "tag": "0002,0010",
                "vr": "UI",
                "vm": "1",
                "len": "18",
                "name": "TransferSyntaxUID"
            }, {
                "_": "1.2.826.0.1.3680043.2.135.1066.101",
                "tag": "0002,0012",
                "vr": "UI",
                "vm": "1",
                "len": "34",
                "name": "ImplementationClassUID"
            }, {
                "_": "1.4.13/WIN32",
                "tag": "0002,0013",
                "vr": "SH",
                "vm": "1",
                "len": "12",
                "name": "ImplementationVersionName"
            }]
        },
        "data-set": {
            "xfer": "1.2.840.10008.1.2",
            "name": "Little Endian Implicit",
            "element": [{
                "_": "520",
                "tag": "0008,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "ISO_IR 100",
                "tag": "0008,0005",
                "vr": "CS",
                "vm": "1",
                "len": "10",
                "name": "SpecificCharacterSet"
            }, {
                "_": "ORIGINAL\\PRIMARY\\",
                "tag": "0008,0008",
                "vr": "CS",
                "vm": "3",
                "len": "18",
                "name": "ImageType"
            }, {
                "_": "1.2.840.10008.5.1.4.1.1.1.2",
                "tag": "0008,0016",
                "vr": "UI",
                "vm": "1",
                "len": "28",
                "name": "SOPClassUID"
            }, {
                "_": "1.2.840.113619.2.227.27331683280.2217131219174320.119",
                "tag": "0008,0018",
                "vr": "UI",
                "vm": "1",
                "len": "54",
                "name": "SOPInstanceUID"
            }, {
                "_": "20131219",
                "tag": "0008,0020",
                "vr": "DA",
                "vm": "1",
                "len": "8",
                "name": "StudyDate"
            }, {
                "_": "20131219",
                "tag": "0008,0021",
                "vr": "DA",
                "vm": "1",
                "len": "8",
                "name": "SeriesDate"
            }, {
                "_": "20131219",
                "tag": "0008,0022",
                "vr": "DA",
                "vm": "1",
                "len": "8",
                "name": "AcquisitionDate"
            }, {
                "_": "20131219",
                "tag": "0008,0023",
                "vr": "DA",
                "vm": "1",
                "len": "8",
                "name": "ContentDate"
            }, {
                "_": "173922.000000",
                "tag": "0008,0030",
                "vr": "TM",
                "vm": "1",
                "len": "14",
                "name": "StudyTime"
            }, {
                "_": "173940.000000",
                "tag": "0008,0031",
                "vr": "TM",
                "vm": "1",
                "len": "14",
                "name": "SeriesTime"
            }, {
                "_": "174317.000000",
                "tag": "0008,0032",
                "vr": "TM",
                "vm": "1",
                "len": "14",
                "name": "AcquisitionTime"
            }, {
                "_": "174320.000000",
                "tag": "0008,0033",
                "vr": "TM",
                "vm": "1",
                "len": "14",
                "name": "ContentTime"
            }, {
                "tag": "0008,0050",
                "vr": "SH",
                "vm": "0",
                "len": "0",
                "name": "AccessionNumber"
            }, {
                "_": "MG",
                "tag": "0008,0060",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "Modality"
            }, {
                "_": "WSD",
                "tag": "0008,0064",
                "vr": "CS",
                "vm": "1",
                "len": "4",
                "name": "ConversionType"
            }, {
                "_": "FOR PRESENTATION",
                "tag": "0008,0068",
                "vr": "CS",
                "vm": "1",
                "len": "16",
                "name": "PresentationIntentType"
            }, {
                "_": "GE MEDICAL SYSTEMS",
                "tag": "0008,0070",
                "vr": "LO",
                "vm": "1",
                "len": "18",
                "name": "Manufacturer"
            }, {
                "_": "SCM LES DAUPHINS",
                "tag": "0008,0080",
                "vr": "LO",
                "vm": "1",
                "len": "16",
                "name": "InstitutionName"
            }, {
                "tag": "0008,0090",
                "vr": "PN",
                "vm": "0",
                "len": "0",
                "name": "ReferringPhysicianName"
            }, {
                "_": "MM01",
                "tag": "0008,1010",
                "vr": "SH",
                "vm": "1",
                "len": "4",
                "name": "StationName"
            }, {
                "_": "BERGE-LEFRANC^Philippe",
                "tag": "0008,1050",
                "vr": "PN",
                "vm": "1",
                "len": "22",
                "name": "PerformingPhysicianName"
            }, {
                "_": "CG",
                "tag": "0008,1070",
                "vr": "PN",
                "vm": "1",
                "len": "2",
                "name": "OperatorsName"
            }, {
                "_": "Senographe Essential VERSION ADS_54.10",
                "tag": "0008,1090",
                "vr": "LO",
                "vm": "1",
                "len": "38",
                "name": "ManufacturerModelName"
            }, {
                "_": "84",
                "tag": "0010,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "BOUSABAT^JIHANE",
                "tag": "0010,0010",
                "vr": "PN",
                "vm": "1",
                "len": "16",
                "name": "PatientName"
            }, {
                "_": "2780374012041",
                "tag": "0010,0020",
                "vr": "LO",
                "vm": "1",
                "len": "14",
                "name": "PatientID"
            }, {
                "_": "19780316",
                "tag": "0010,0030",
                "vr": "DA",
                "vm": "1",
                "len": "8",
                "name": "PatientBirthDate"
            }, {
                "_": "F",
                "tag": "0010,0040",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "PatientSex"
            }, {
                "_": "035Y",
                "tag": "0010,1010",
                "vr": "AS",
                "vm": "1",
                "len": "4",
                "name": "PatientAge"
            }, {
                "_": "916",
                "tag": "0018,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "BREAST",
                "tag": "0018,0015",
                "vr": "CS",
                "vm": "1",
                "len": "6",
                "name": "BodyPartExamined"
            }, {
                "_": "29",
                "tag": "0018,0060",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "KVP"
            }, {
                "_": "27331683280",
                "tag": "0018,1000",
                "vr": "LO",
                "vm": "1",
                "len": "12",
                "name": "DeviceSerialNumber"
            }, {
                "_": "Ads Application Package VERSION ADS_54.10",
                "tag": "0018,1020",
                "vr": "LO",
                "vm": "1",
                "len": "42",
                "name": "SoftwareVersions"
            }, {
                "_": "ROUTINE",
                "tag": "0018,1030",
                "vr": "LO",
                "vm": "1",
                "len": "8",
                "name": "ProtocolName"
            }, {
                "_": "660",
                "tag": "0018,1110",
                "vr": "DS",
                "vm": "1",
                "len": "4",
                "name": "DistanceSourceToDetector"
            }, {
                "_": "660",
                "tag": "0018,1111",
                "vr": "DS",
                "vm": "1",
                "len": "4",
                "name": "DistanceSourceToPatient"
            }, {
                "_": "1",
                "tag": "0018,1114",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "EstimatedRadiographicMagnificationFactor"
            }, {
                "_": "RECTANGLE",
                "tag": "0018,1147",
                "vr": "CS",
                "vm": "1",
                "len": "10",
                "name": "FieldOfViewShape"
            }, {
                "_": "229\\191",
                "tag": "0018,1149",
                "vr": "IS",
                "vm": "2",
                "len": "8",
                "name": "FieldOfViewDimensions"
            }, {
                "_": "515",
                "tag": "0018,1150",
                "vr": "IS",
                "vm": "1",
                "len": "4",
                "name": "ExposureTime"
            }, {
                "_": "61",
                "tag": "0018,1151",
                "vr": "IS",
                "vm": "1",
                "len": "2",
                "name": "XRayTubeCurrent"
            }, {
                "_": "32",
                "tag": "0018,1152",
                "vr": "IS",
                "vm": "1",
                "len": "2",
                "name": "Exposure"
            }, {
                "_": "32000",
                "tag": "0018,1153",
                "vr": "IS",
                "vm": "1",
                "len": "6",
                "name": "ExposureInuAs"
            }, {
                "_": "STRIP",
                "tag": "0018,1160",
                "vr": "SH",
                "vm": "1",
                "len": "6",
                "name": "FilterType"
            }, {
                "_": "0.09409090909091\\0.09409090909091",
                "tag": "0018,1164",
                "vr": "DS",
                "vm": "2",
                "len": "34",
                "name": "ImagerPixelSpacing"
            }, {
                "_": "RECIPROCATING\\FOCUSED",
                "tag": "0018,1166",
                "vr": "CS",
                "vm": "2",
                "len": "22",
                "name": "Grid"
            }, {
                "_": "0.3",
                "tag": "0018,1190",
                "vr": "DS",
                "vm": "1",
                "len": "4",
                "name": "FocalSpots"
            }, {
                "_": "RHODIUM",
                "tag": "0018,1191",
                "vr": "CS",
                "vm": "1",
                "len": "8",
                "name": "AnodeTargetMaterial"
            }, {
                "_": "61",
                "tag": "0018,11a0",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "BodyPartThickness"
            }, {
                "_": "60",
                "tag": "0018,11a2",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "CompressionForce"
            }, {
                "_": "PREMIUM_VIEW",
                "tag": "0018,1400",
                "vr": "LO",
                "vm": "1",
                "len": "12",
                "name": "AcquisitionDeviceProcessingDescription"
            }, {
                "_": "GEMS_FFDM_PV",
                "tag": "0018,1401",
                "vr": "LO",
                "vm": "1",
                "len": "12",
                "name": "AcquisitionDeviceProcessingCode"
            }, {
                "_": "3038",
                "tag": "0018,1405",
                "vr": "IS",
                "vm": "1",
                "len": "4",
                "name": "RelativeXRayExposure"
            }, {
                "_": "MAMMOGRAPHIC",
                "tag": "0018,1508",
                "vr": "CS",
                "vm": "1",
                "len": "12",
                "name": "PositionerType"
            }, {
                "_": "45",
                "tag": "0018,1510",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "PositionerPrimaryAngle"
            }, {
                "_": "0",
                "tag": "0018,1531",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "DetectorSecondaryAngle"
            }, {
                "_": "RECTANGULAR",
                "tag": "0018,1700",
                "vr": "CS",
                "vm": "1",
                "len": "12",
                "name": "CollimatorShape"
            }, {
                "_": "0",
                "tag": "0018,1702",
                "vr": "IS",
                "vm": "1",
                "len": "2",
                "name": "CollimatorLeftVerticalEdge"
            }, {
                "_": "1915",
                "tag": "0018,1704",
                "vr": "IS",
                "vm": "1",
                "len": "4",
                "name": "CollimatorRightVerticalEdge"
            }, {
                "_": "0",
                "tag": "0018,1706",
                "vr": "IS",
                "vm": "1",
                "len": "2",
                "name": "CollimatorUpperHorizontalEdge"
            }, {
                "_": "2295",
                "tag": "0018,1708",
                "vr": "IS",
                "vm": "1",
                "len": "4",
                "name": "CollimatorLowerHorizontalEdge"
            }, {
                "_": "MLO",
                "tag": "0018,5101",
                "vr": "CS",
                "vm": "1",
                "len": "4",
                "name": "ViewPosition"
            }, {
                "_": "0.00790327973664",
                "tag": "0018,6000",
                "vr": "DS",
                "vm": "1",
                "len": "16",
                "name": "Sensitivity"
            }, {
                "_": "YES",
                "tag": "0018,7000",
                "vr": "CS",
                "vm": "1",
                "len": "4",
                "name": "DetectorConditionsNominalFlag"
            }, {
                "_": "30.394599914551",
                "tag": "0018,7001",
                "vr": "DS",
                "vm": "1",
                "len": "16",
                "name": "DetectorTemperature"
            }, {
                "_": "SCINTILLATOR",
                "tag": "0018,7004",
                "vr": "CS",
                "vm": "1",
                "len": "12",
                "name": "DetectorType"
            }, {
                "_": "AREA",
                "tag": "0018,7005",
                "vr": "CS",
                "vm": "1",
                "len": "4",
                "name": "DetectorConfiguration"
            }, {
                "_": "DETECTOR VERSION 2.0 NOTMTFCOMP",
                "tag": "0018,7006",
                "vr": "LT",
                "vm": "1",
                "len": "32",
                "name": "DetectorDescription"
            }, {
                "_": "NPL0130_06",
                "tag": "0018,700a",
                "vr": "SH",
                "vm": "1",
                "len": "10",
                "name": "DetectorID"
            }, {
                "_": "20130820",
                "tag": "0018,700c",
                "vr": "DA",
                "vm": "1",
                "len": "8",
                "name": "DateOfLastDetectorCalibration"
            }, {
                "_": "1\\1",
                "tag": "0018,701a",
                "vr": "DS",
                "vm": "2",
                "len": "4",
                "name": "DetectorBinning"
            }, {
                "_": "0.1\\0.1",
                "tag": "0018,7020",
                "vr": "DS",
                "vm": "2",
                "len": "8",
                "name": "DetectorElementPhysicalSize"
            }, {
                "_": "0.1\\0.1",
                "tag": "0018,7022",
                "vr": "DS",
                "vm": "2",
                "len": "8",
                "name": "DetectorElementSpacing"
            }, {
                "_": "RECTANGLE",
                "tag": "0018,7024",
                "vr": "CS",
                "vm": "1",
                "len": "10",
                "name": "DetectorActiveShape"
            }, {
                "_": "307.2\\240",
                "tag": "0018,7026",
                "vr": "DS",
                "vm": "2",
                "len": "10",
                "name": "DetectorActiveDimensions"
            }, {
                "_": "5\\1",
                "tag": "0018,7030",
                "vr": "DS",
                "vm": "2",
                "len": "4",
                "name": "FieldOfViewOrigin"
            }, {
                "_": "180",
                "tag": "0018,7032",
                "vr": "DS",
                "vm": "1",
                "len": "4",
                "name": "FieldOfViewRotation"
            }, {
                "_": "NO",
                "tag": "0018,7034",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "FieldOfViewHorizontalFlip"
            }, {
                "_": "RHODIUM",
                "tag": "0018,7050",
                "vr": "CS",
                "vm": "1",
                "len": "8",
                "name": "FilterMaterial"
            }, {
                "_": "MANUAL",
                "tag": "0018,7060",
                "vr": "CS",
                "vm": "1",
                "len": "6",
                "name": "ExposureControlMode"
            }, {
                "_": "AOP contrast RECTANGLE 0 mm 0 mm 0 mm 0 mm EXP DOSE -2 nGy",
                "tag": "0018,7062",
                "vr": "LT",
                "vm": "1",
                "len": "58",
                "name": "ExposureControlModeDescription"
            }, {
                "_": "NORMAL",
                "tag": "0018,7064",
                "vr": "CS",
                "vm": "1",
                "len": "6",
                "name": "ExposureStatus"
            }, {
                "_": "186",
                "tag": "0020,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "1.2.840.113619.2.227.27331683280.12596131219173922.20000",
                "tag": "0020,000d",
                "vr": "UI",
                "vm": "1",
                "len": "56",
                "name": "StudyInstanceUID"
            }, {
                "_": "1.2.840.113619.2.227.27331683280.12596131219173940.10005",
                "tag": "0020,000e",
                "vr": "UI",
                "vm": "1",
                "len": "56",
                "name": "SeriesInstanceUID"
            }, {
                "_": "5540",
                "tag": "0020,0010",
                "vr": "SH",
                "vm": "1",
                "len": "4",
                "name": "StudyID"
            }, {
                "_": "15710",
                "tag": "0020,0011",
                "vr": "IS",
                "vm": "1",
                "len": "6",
                "name": "SeriesNumber"
            }, {
                "_": "4",
                "tag": "0020,0013",
                "vr": "IS",
                "vm": "1",
                "len": "2",
                "name": "InstanceNumber"
            }, {
                "_": "P\\FL",
                "tag": "0020,0020",
                "vr": "CS",
                "vm": "2",
                "len": "4",
                "name": "PatientOrientation"
            }, {
                "_": "R",
                "tag": "0020,0062",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "ImageLaterality"
            }, {
                "_": "314",
                "tag": "0028,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "1",
                "tag": "0028,0002",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "SamplesPerPixel"
            }, {
                "_": "MONOCHROME2",
                "tag": "0028,0004",
                "vr": "CS",
                "vm": "1",
                "len": "12",
                "name": "PhotometricInterpretation"
            }, {
                "_": "2294",
                "tag": "0028,0010",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "Rows"
            }, {
                "_": "1914",
                "tag": "0028,0011",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "Columns"
            }, {
                "_": "16",
                "tag": "0028,0100",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "BitsAllocated"
            }, {
                "_": "12",
                "tag": "0028,0101",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "BitsStored"
            }, {
                "_": "11",
                "tag": "0028,0102",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "HighBit"
            }, {
                "_": "0",
                "tag": "0028,0103",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "PixelRepresentation"
            }, {
                "_": "0",
                "tag": "0028,0120",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "PixelPaddingValue"
            }, {
                "_": "658",
                "tag": "0028,0121",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "PixelPaddingRangeLimit"
            }, {
                "_": "NO",
                "tag": "0028,0300",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "QualityControlImage"
            }, {
                "_": "NO",
                "tag": "0028,0301",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "BurnedInAnnotation"
            }, {
                "_": "LOG",
                "tag": "0028,1040",
                "vr": "CS",
                "vm": "1",
                "len": "4",
                "name": "PixelIntensityRelationship"
            }, {
                "_": "-1",
                "tag": "0028,1041",
                "vr": "SS",
                "vm": "1",
                "len": "2",
                "name": "PixelIntensityRelationshipSign"
            }, {
                "_": "3703\\3745\\3631\\3907",
                "tag": "0028,1050",
                "vr": "DS",
                "vm": "4",
                "len": "20",
                "name": "WindowCenter"
            }, {
                "_": "900\\750\\1050\\1671",
                "tag": "0028,1051",
                "vr": "DS",
                "vm": "4",
                "len": "18",
                "name": "WindowWidth"
            }, {
                "_": "0",
                "tag": "0028,1052",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "RescaleIntercept"
            }, {
                "_": "1",
                "tag": "0028,1053",
                "vr": "DS",
                "vm": "1",
                "len": "2",
                "name": "RescaleSlope"
            }, {
                "_": "US",
                "tag": "0028,1054",
                "vr": "LO",
                "vm": "1",
                "len": "2",
                "name": "RescaleType"
            }, {
                "_": "NORMAL\\HARDER\\SOFTER\\USER",
                "tag": "0028,1055",
                "vr": "LO",
                "vm": "4",
                "len": "26",
                "name": "WindowCenterWidthExplanation"
            }, {
                "_": "SIGMOID",
                "tag": "0028,1056",
                "vr": "CS",
                "vm": "1",
                "len": "8",
                "name": "VOILUTFunction"
            }, {
                "_": "NO",
                "tag": "0028,1300",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "BreastImplantPresent"
            }, {
                "_": "00",
                "tag": "0028,2110",
                "vr": "CS",
                "vm": "1",
                "len": "2",
                "name": "LossyImageCompression"
            }, {
                "_": "86",
                "tag": "0040,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "0",
                "tag": "0040,0302",
                "vr": "US",
                "vm": "1",
                "len": "2",
                "name": "EntranceDose"
            }, {
                "_": "599",
                "tag": "0040,0306",
                "vr": "DS",
                "vm": "1",
                "len": "4",
                "name": "DistanceSourceToEntrance"
            }, {
                "_": "50 %",
                "tag": "0040,0310",
                "vr": "ST",
                "vm": "1",
                "len": "4",
                "name": "CommentsOnRadiationDose"
            }, {
                "_": "0.00593",
                "tag": "0040,0316",
                "vr": "DS",
                "vm": "1",
                "len": "8",
                "name": "OrganDose"
            }, {
                "_": "BREAST",
                "tag": "0040,0318",
                "vr": "CS",
                "vm": "1",
                "len": "6",
                "name": "OrganExposed"
            }, {
                "_": "3.038",
                "tag": "0040,8302",
                "vr": "DS",
                "vm": "1",
                "len": "6",
                "name": "EntranceDoseInmGy"
            }, {
                "_": "5538",
                "tag": "0045,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "PrivateGroupLength"
            }, {
                "_": "GEMS_SENO_02",
                "tag": "0045,0010",
                "vr": "LO",
                "vm": "1",
                "len": "12",
                "name": "PrivateCreator"
            }, {
                "tag": "0045,1006",
                "vr": "??",
                "vm": "1",
                "len": "2",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,101b",
                "vr": "??",
                "vm": "1",
                "len": "4",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1020",
                "vr": "??",
                "vm": "1",
                "len": "16",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1026",
                "vr": "??",
                "vm": "1",
                "len": "1024",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1029",
                "vr": "??",
                "vm": "1",
                "len": "20",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,102a",
                "vr": "??",
                "vm": "1",
                "len": "12",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,102b",
                "vr": "??",
                "vm": "1",
                "len": "12",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1049",
                "vr": "??",
                "vm": "1",
                "len": "2",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1050",
                "vr": "??",
                "vm": "1",
                "len": "54",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1051",
                "vr": "??",
                "vm": "1",
                "len": "56",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1058",
                "vr": "??",
                "vm": "1",
                "len": "16",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1059",
                "vr": "??",
                "vm": "1",
                "len": "4",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1060",
                "vr": "??",
                "vm": "1",
                "len": "18",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1061",
                "vr": "??",
                "vm": "1",
                "len": "14",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1064",
                "vr": "??",
                "vm": "1",
                "len": "4",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1071",
                "vr": "??",
                "vm": "1",
                "len": "4096",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1072",
                "vr": "??",
                "vm": "1",
                "len": "6",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "tag": "0045,1090",
                "vr": "??",
                "vm": "1",
                "len": "14",
                "name": "Unknown Tag & Data",
                "binary": "hidden"
            }, {
                "_": "8",
                "tag": "0054,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "8",
                "tag": "0088,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "16",
                "tag": "2050,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "GenericGroupLength"
            }, {
                "_": "IDENTITY",
                "tag": "2050,0020",
                "vr": "CS",
                "vm": "1",
                "len": "8",
                "name": "PresentationLUTShape"
            }, {
                "_": "8781440",
                "tag": "7fe0,0000",
                "vr": "UL",
                "vm": "1",
                "len": "4",
                "name": "ACR_NEMA_2C_VariablePixelDataGroupLength"
            }, {
                "tag": "7fe0,0010",
                "vr": "OW",
                "vm": "1",
                "len": "8781432",
                "name": "PixelData",
                "loaded": "no",
                "binary": "hidden"
            }],
            "sequence": [{
                "tag": "0008,2112",
                "vr": "SQ",
                "card": "1",
                "name": "SourceImageSequence",
                "item": {
                    "card": "3",
                    "element": [{
                        "_": "1.2.840.10008.5.1.4.1.1.1.2.1",
                        "tag": "0008,1150",
                        "vr": "UI",
                        "vm": "1",
                        "len": "30",
                        "name": "ReferencedSOPClassUID"
                    }, {
                        "_": "1.2.840.113619.2.227.27331683280.2217131219174320.117",
                        "tag": "0008,1155",
                        "vr": "UI",
                        "vm": "1",
                        "len": "54",
                        "name": "ReferencedSOPInstanceUID"
                    }, {
                        "_": "YES",
                        "tag": "0028,135a",
                        "vr": "CS",
                        "vm": "1",
                        "len": "4",
                        "name": "SpatialLocationsPreserved"
                    }]
                }
            }, {
                "tag": "0008,2218",
                "vr": "SQ",
                "card": "1",
                "name": "AnatomicRegionSequence",
                "item": {
                    "card": "3",
                    "element": [{
                        "_": "T-04000",
                        "tag": "0008,0100",
                        "vr": "SH",
                        "vm": "1",
                        "len": "8",
                        "name": "CodeValue"
                    }, {
                        "_": "SNM3",
                        "tag": "0008,0102",
                        "vr": "SH",
                        "vm": "1",
                        "len": "4",
                        "name": "CodingSchemeDesignator"
                    }, {
                        "_": "BREAST",
                        "tag": "0008,0104",
                        "vr": "LO",
                        "vm": "1",
                        "len": "6",
                        "name": "CodeMeaning"
                    }]
                }
            }, {
                "tag": "0028,3010",
                "vr": "SQ",
                "card": "4",
                "name": "VOILUTSequence",
                "item": [{
                    "card": "3",
                    "element": [{
                        "_": "2421\\1675\\12",
                        "tag": "0028,3002",
                        "vr": "xs",
                        "vm": "3",
                        "len": "6",
                        "name": "LUTDescriptor"
                    }, {
                        "_": "NORMAL",
                        "tag": "0028,3003",
                        "vr": "LO",
                        "vm": "1",
                        "len": "6",
                        "name": "LUTExplanation"
                    }, {
                        "tag": "0028,3006",
                        "vr": "lt",
                        "vm": "1",
                        "len": "4842",
                        "name": "LUTData",
                        "loaded": "no",
                        "binary": "hidden"
                    }]
                }, {
                    "card": "3",
                    "element": [{
                        "_": "2041\\2055\\12",
                        "tag": "0028,3002",
                        "vr": "xs",
                        "vm": "3",
                        "len": "6",
                        "name": "LUTDescriptor"
                    }, {
                        "_": "HARDER",
                        "tag": "0028,3003",
                        "vr": "LO",
                        "vm": "1",
                        "len": "6",
                        "name": "LUTExplanation"
                    }, {
                        "tag": "0028,3006",
                        "vr": "lt",
                        "vm": "1",
                        "len": "4082",
                        "name": "LUTData",
                        "binary": "hidden"
                    }]
                }, {
                    "card": "3",
                    "element": [{
                        "_": "2831\\1265\\12",
                        "tag": "0028,3002",
                        "vr": "xs",
                        "vm": "3",
                        "len": "6",
                        "name": "LUTDescriptor"
                    }, {
                        "_": "SOFTER",
                        "tag": "0028,3003",
                        "vr": "LO",
                        "vm": "1",
                        "len": "6",
                        "name": "LUTExplanation"
                    }, {
                        "tag": "0028,3006",
                        "vr": "lt",
                        "vm": "1",
                        "len": "5662",
                        "name": "LUTData",
                        "loaded": "no",
                        "binary": "hidden"
                    }]
                }, {
                    "card": "3",
                    "element": [{
                        "_": "3954\\142\\12",
                        "tag": "0028,3002",
                        "vr": "xs",
                        "vm": "3",
                        "len": "6",
                        "name": "LUTDescriptor"
                    }, {
                        "_": "USER",
                        "tag": "0028,3003",
                        "vr": "LO",
                        "vm": "1",
                        "len": "4",
                        "name": "LUTExplanation"
                    }, {
                        "tag": "0028,3006",
                        "vr": "lt",
                        "vm": "1",
                        "len": "7908",
                        "name": "LUTData",
                        "loaded": "no",
                        "binary": "hidden"
                    }]
                }]
            }, {
                "tag": "0040,0555",
                "vr": "SQ",
                "card": "0",
                "len": "0",
                "name": "AcquisitionContextSequence"
            }, {
                "tag": "0054,0220",
                "vr": "SQ",
                "card": "1",
                "name": "ViewCodeSequence",
                "item": {
                    "card": "4",
                    "element": [{
                        "_": "R-10226",
                        "tag": "0008,0100",
                        "vr": "SH",
                        "vm": "1",
                        "len": "8",
                        "name": "CodeValue"
                    }, {
                        "_": "SNM3",
                        "tag": "0008,0102",
                        "vr": "SH",
                        "vm": "1",
                        "len": "4",
                        "name": "CodingSchemeDesignator"
                    }, {
                        "_": "medio-lateral oblique",
                        "tag": "0008,0104",
                        "vr": "LO",
                        "vm": "1",
                        "len": "22",
                        "name": "CodeMeaning"
                    }],
                    "sequence": {
                        "tag": "0054,0222",
                        "vr": "SQ",
                        "card": "0",
                        "len": "0",
                        "name": "ViewModifierCodeSequence"
                    }
                }
            }, {
                "tag": "0088,0200",
                "vr": "SQ",
                "card": "1",
                "name": "IconImageSequence",
                "item": {
                    "card": "9",
                    "element": [{
                        "_": "1",
                        "tag": "0028,0002",
                        "vr": "US",
                        "vm": "1",
                        "len": "2",
                        "name": "SamplesPerPixel"
                    }, {
                        "_": "MONOCHROME2",
                        "tag": "0028,0004",
                        "vr": "CS",
                        "vm": "1",
                        "len": "12",
                        "name": "PhotometricInterpretation"
                    }, {
                        "_": "64",
                        "tag": "0028,0010",
                        "vr": "US",
                        "vm": "1",
                        "len": "2",
                        "name": "Rows"
                    }, {
                        "_": "53",
                        "tag": "0028,0011",
                        "vr": "US",
                        "vm": "1",
                        "len": "2",
                        "name": "Columns"
                    }, {
                        "_": "8",
                        "tag": "0028,0100",
                        "vr": "US",
                        "vm": "1",
                        "len": "2",
                        "name": "BitsAllocated"
                    }, {
                        "_": "8",
                        "tag": "0028,0101",
                        "vr": "US",
                        "vm": "1",
                        "len": "2",
                        "name": "BitsStored"
                    }, {
                        "_": "7",
                        "tag": "0028,0102",
                        "vr": "US",
                        "vm": "1",
                        "len": "2",
                        "name": "HighBit"
                    }, {
                        "_": "0",
                        "tag": "0028,0103",
                        "vr": "US",
                        "vm": "1",
                        "len": "2",
                        "name": "PixelRepresentation"
                    }, {
                        "tag": "7fe0,0010",
                        "vr": "OW",
                        "vm": "1",
                        "len": "3392",
                        "name": "PixelData",
                        "binary": "hidden"
                    }]
                }
            }]
        }
    }
}